### PR TITLE
temporary local copy of fix for HVM/paravirtual issue on AWS

### PR DESCRIPTION
**Pull request by ahgittin**
fixes https://issues.apache.org/jira/browse/BROOKLYN-140

as noted, when new jclouds lands we should revert this

@duncangrant can you let us know if this fixes your problem?

### CODE REVIEW

**Comment by ahgittin** [comment]
i've confirmed with this PR i can create an instance with `hardwareId: r3.large` which is one of the types which does only hvm.

note that this may introduce some changed default images, with more changed default images landing with the next jclouds (when new generation instance types are preferred). /cc @aledsage

**Comment by aledsage** [comment]
Build fails with:

    [INFO] There are 1 checkstyle errors.
    [ERROR] EC2HardwareBuilder.java[686:1] (whitespace) FileTabCharacter: Line contains a tab character.

**Comment by aledsage** [comment]
This fix is non-deterministic. There is no guarantee of classpath order, for whether the jclouds class or the replacement class will be first on the classpath. It would need to be created as a patch, and added to the `lib/patch/` dir to guarantee classpath ordering.

**Comment by ahgittin** [comment]
isn't it going to be loaded either in alphabetical order (release) or maven order (ide) ?

so i think it *is* deterministic.  slightly naughty but pragmatic, for a temporary fix.  (haven't we used this trick before for overriding jclouds items (gce in particular)?  the only times problems i'm aware of problems is when the overriding jar filename comes first alphabetically.)

**Comment by ahgittin** [comment]
btw - fixed checkstyle (tab from jclouds project).  also have confirmation from @duncangrant that this fixes his problem case.

**Comment by neykov** [comment]
Good point by @aledsage , agree with him. We already had an issue with jars ordered differently - one of the jars was shadowing the others, but only if it was before them in the classpath.

**Comment by aledsage** [comment]
For jar ordering, it is deterministic on a given platform+jvm but different platforms seem to order it differently. There was a fix done like this one before that worked fine locally but then failed when Brooklyn was run on (if I recall correctly) ubuntu with OpenJDK.

This relates to the distro, with the classpath set to include `lib/brooklyn/*.jar`. Ordering in IDEs probably behave completely differently again, as might maven command line builds.

**Comment by ahgittin** [comment]
@aledsage should we add a `lib/deps/` dir and order the `dist` classpath so that `lib/brooklyn/*.jar` is first?  that seems the easiest way to solve issues with the dist.  i'd rather not introduce a patch projects.  or as most environments seem to work we could just leave it as is and accept that the aws `hvm` error might remain an issue in some cases until we have a new jclouds cut.

**Comment by neykov** [comment]
Any way we can make the patch work transparently for downstream projects as well? Can't see how it could be approached.

Having `lib/deps` would be fine for Brooklyn, but downstream projects will face the same problem again, because `brooklyn-location-jclouds` will be mixed with the other dependencies.
I like the idea of a separate patches project, with each downstream making sure it puts it in its patches folder. This won't be the last time there is need to override a dependency, so why not go all the way and make it robust. It's a one time change so next time patching will be transparent.

**Comment by ahgittin** [comment]
Downstream patches could be an elegant solution but I can't help feeling we're trying to do too much.  Maintaining a patch dir downstream which grabs patches from upstream feels like a lot of work which is best avoided.  Also it won't solve any errors which occur if the downstream project is being run from the IDE.

That said I'm not convinced these errors are severe because both maven order and alpha order give us the desired result and those are the majority strategies.

The right way to support a downstream project, would be to take a tagged jclouds cut with this patch.  I'd rather invest in that if required than passing patches, I think.  (But even that I don't think is urgent.)

However happy to be overruled if @aledsage feels strongly.

**Comment by ahgittin** [comment]
@aledsage bump. could we merge this before someone else hits hvm issues and if a full-blown patches project is needed we do that (or resolve it with one of the other techniques above).

**Comment by ahgittin** [comment]
merging this; if we want to do a better patching strategy we can shortly

**Pull request merged**
