### PR TITLE
[WIP] Pluggable YAML parsers

### PR DESCRIPTION
**Pull request by neykov**
Rebases https://github.com/apache/incubator-brooklyn/pull/100 against master (as of beginning of December). The updates are needed for the TOSCA implementation.

### CODE REVIEW

**Comment by neykov** [comment]
Failure unrelated, merge conflict resolving needed anyway.

**Comment by grkvlt** [comment]
# Question

Is there a way to extend this with a mechanism to enable pluggable _extensions_ to YAML parsers. For example, I am happy with using the CAMP parser, but I want to allow the YAML files to be able to include service types like `docker:`_imageId_`:`_tag_ instead of Java class names. The parsing would be part of an external library, in this instance [Clocker](http://clocker.io/), since the entities created for these service types would be defined there, and core Brooklyn has no way of referencing the classes driectly.

**Comment by neykov** [comment]
This should be easy to achieve using the same approach (ServiceLoader), by replacing the hard-coded resolvers in `io.brooklyn.camp.brooklyn.spi.creation.BrooklynComponentTemplateResolver.Factory.computeResolverType`. It's unrelated to this PR though as it's on another level of abstraction.

**Comment by andreaturli** [comment]
@ahgittin do you think we should try to rebase this PR? I guess for things like TOSCA may really be the way to go? Any suggestions?

**Comment by neykov** [comment]
Closing in favour of https://github.com/apache/incubator-brooklyn/pull/760.

**Pull request closed without merging**
