### PR TITLE
[BROOKLYN-162] Renaming package brooklyn.location

### PR DESCRIPTION
**Pull request by bostko**

### CODE REVIEW

**Comment by hzbarcea** [comment]
@bostko I saw what you did in this pull request too late. The build failed because you missed a couple of imports in the quickstart archetype, but by now I think I created a bunch of conflicts with the last commits. For the package rename I think we should go straight to using the convention we agreed upon to avoid the split package problem.

I don't know if you want to rework this. If not that's ok, I can take care of it.

**Comment by bostko** [comment]
@hzbarcea I saw it. You can test now.

**Comment by CMoH** [comment]
Tested - I was able to successfully install various sample blueprints. Good for merge.

**Comment by hzbarcea** [comment]
Merged into #825, conflicts resolved, moved ./api/location to the proper location, tests pass, merged.

**Comment by hzbarcea** [comment]
@bostko , for some reason this wasn't closed automatically, can you please close it manually?

**Pull request closed without merging**
