### PR TITLE
[WIP] Rebase of PR #1140 onto incubator-brooklyn master

### PR DESCRIPTION
**Pull request by CMoH**
This is a rebase of #1140 onto incubator-brooklyn's master with the purpose of applying the changes onto the new repos (non-incubating). I hope I managed to preserve the changes made onto master while merging CXF changes. I left #1140 untouched for reference.

### CODE REVIEW

**Comment by CMoH** [comment]
@neykov When finishing up I ran into the same problem with the DefaultExceptionMapper as in #1140. Do you know anything about that?

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project brooklyn-rest-resources: Compilation failure: Compilation failure:
[ERROR] /home/cipi/src/incubator-brooklyn/brooklyn-server/rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/DefaultExceptionMapper.java:[41,28] package org.eclipse.jetty.io does not exist
[ERROR] /home/cipi/src/incubator-brooklyn/brooklyn-server/rest/rest-resources/src/main/java/org/apache/brooklyn/rest/util/DefaultExceptionMapper.java:[61,35] cannot find symbol
[ERROR] symbol:   class EofException
[ERROR] location: class org.apache.brooklyn.rest.util.DefaultExceptionMapper
```

**Comment by neykov** [comment]
@CMoH https://github.com/CMoH/incubator-brooklyn/pull/7 includes a fix for this as well.

**Comment by ahgittin** [comment]
@CMoH @neykov probably if you experiment w git diff + patch you could find a way to move multiple commits across to the split repos keeping separate commits without too much overhead.  i didn't look in to it because i didn't need it but it might be useful here.  (tho i'm also happy if you just want to squash...)

**Comment by neykov** [comment]
Don't mind squashing my commits into CMoH's. Definitely would like squashing all of mine into a single commit.

**Comment by CMoH** [comment]
I also agree transporting the changes as a single patch onto the new repos.

**Pull request closed without merging**
