### PR TITLE
Better group member display

### PR DESCRIPTION
**Pull request by alasdairhodge**
* Display group members alongside children.
* Each entity still has one "direct" position in the hierarchy, but may also have several "indirect" references.
* Indirect nodes can be interacted with in-place as normal:
  * show details, invoke effectors, expand children, etc.
* Indirect subordinates have a distinct visual style to avoid confusion.

@grkvlt: Would love to know if this plays well with Clocker, which I know makes heavy use of groups.

screen shot 2015-10-01 at 15 31 41

### CODE REVIEW

**Comment by aledsage** [comment]
Thanks @alasdairhodge 

I like the curved arrow icon and greyer text - a nice way to represent that they are children.

My concern is what happens when someone expands one of these indirect nodes to see its children and members. I presume everything below it keeps that same look (the icon + grey text). So how does someone tell the difference between a child and a member of an indirect node?

Throwing around some other ideas... we could have sub-headings for "children" and "members". That would take up a lot of space unfortunately, but would also be extensible for other relationships (e.g. showing the locations of an entity, or other dependencies).

@morganbrooke any comments on how best to represent this?

**Comment by ahgittin** [comment]
feels great for now.

longer term i'd like to have a graphical view (not a tree view) which allows for multiple types of relationships, including "managed child" (which is what we'd inject the current hierarchy into), rather than try to make this tree all-singing-all-dancing.

**Comment by alasdairhodge** [comment]
Thanks for reviewing, @aledsage and @ahgittin. I deliberately only distinguished between "direct" and "indirect" subordinates, anticipating several "indirect" relationship types in the future. Will keep an eye out for cases where this new approach is confusing and refine accordingly.

**Comment by alasdairhodge** [comment]
We should now (arguably) remove `DelegateEntity` and `AbstractGroup.MEMBER_DELEGATE_*` (following a deprecation cycle as none are `@Beta`). Might also be a good time to remove the ill-conceived `FIRST_MEMBER` from `AbstractGroup`.

**Comment by ahgittin** [comment]
+1

On 08/10/2015 14:17, Alasdair Hodge wrote:
>
> We should now (arguably) remove |DelegateEntity| and 
> |AbstractGroup.MEMBER_DELEGATE_*| (following a deprecation cycle as 
> none are |@Beta|). Might also be a good time to remove the 
> ill-conceived |FIRST_MEMBER| from |AbstractGroup|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/apache/incubator-brooklyn/pull/929#issuecomment-146541901>.
>


-- 
Cloudsoft Corporation Limited, Registered in Scotland No: SC349230. 
 Registered Office: 13 Dryden Place, Edinburgh, EH9 1RP
 
This e-mail message is confidential and for use by the addressee only. If 
the message is received by anyone other than the addressee, please return 
the message to the sender by replying to it and then delete the message 
from your computer. Internet e-mails are not necessarily secure. Cloudsoft 
Corporation Limited does not accept responsibility for changes made to this 
message after it was sent.

Whilst all reasonable care has been taken to avoid the transmission of 
viruses, it is the responsibility of the recipient to ensure that the 
onward transmission, opening or use of this message and any attachments 
will not adversely affect its systems or data. No responsibility is 
accepted by Cloudsoft Corporation Limited in this regard and the recipient 
should carry out such virus and other checks as it considers appropriate.

**Comment by morganbrooke** [comment]
SO I think you're saying that you want that 2nd parent element in BasicStartables to stand out more?

You put a 1px dark gray border around each group but I think the background color is a pretty good indication of what belongs to what.

**Comment by morganbrooke** [comment]
+1

**Comment by alasdairhodge** [comment]
Paraphrasing: for regular nodes, members ("indirect" subordinates) are visually distinguishable from children ("direct" subordinates) due to the indirection arrow. However, for indirect nodes, children and members are indistinguishable. One could argue that indirect subs of an indirect node are "doubly-indirect" and style accordingly, but that could get ridiculous.

Alternatively, we could add *another* indicator to distinguish "child" vs "member" (vs "other relationship" in the future?), somehow in combination with the arrow, but I'd be very wary about overcooking it. Happy to review any suggestions.

**Pull request merged**
