### PR TITLE
Restore old HttpTool / Response  for backward compatibility

### PR DESCRIPTION
**Pull request by geomacy**
PR follow-up to comment https://github.com/apache/incubator-brooklyn/pull/994#discussion_r44706399

### CODE REVIEW

**Comment by neykov** [comment]
Thanks @geomacy, merging.

**Comment by neykov** [comment]
Did some more testing, unfortunately this doesn't fully solve the problem. Will hold off merging so we can further discuss it. The changes here are perfectly good though, but not enough.

There's an API that's heavilty used in entities - `HttpFeed` and related (i.e. `HttpValueFunction`, `HttpPollConfig`). The package renaming changes the signature of the methods in these classes so that already compiled entities against pre-changes version will not be compatible with post-changes versions. Probably worth moving to the dev list.

**Comment by aledsage** [comment]
Thanks @geomacy - I'd also include a comment at the top of each of those classes to explain why the code is still there (rather than the "extends" mechanism). For example, copy-paste part of Svet's comment from https://github.com/apache/incubator-brooklyn/pull/994#discussion_r44706399.

**Comment by geomacy** [comment]
Will do that,  thanks Aled.

G

**Comment by ahgittin** [comment]
As discussed on mailing list, I'm against.  Short of introducing alternates for every call which references these classes, it's impossible to completely preserve backwards binary compatibility for these changes.  The halfway house of leaving it as was (closing this) and putting a comment in the release notes seems the pragmatic choice.

**Comment by geomacy** [comment]
Ok, I shall leave this as-is then.

**Comment by geomacy** [comment]
Or rather, should I just close this pull request?

**Comment by ahgittin** [comment]
My suggestion is to close this.  @neykov @aledsage you agree?

**Comment by neykov** [comment]
No strong opinion on the backwards compatibility. What I'd like though is to either merge this or completely remove HttpTool in core (just leaving a shell class with a javadoc which points to the new one). This way we won't have an HttpTool in core, returning HttpToolResponse from utils.

**Comment by ahgittin** [comment]
@neykov fine with your plans to gut `HttpTool` core, rather than allow it to (surprisingly) return the new non-core `HttpToolResponse`

@geomacy can you do that?

**Comment by geomacy** [comment]
i.e. remove it altogether?  Yes, I'll update the pull request accordingly.

**Comment by geomacy** [comment]
I've updated the core tool and response classes in [14945f7](https://github.com/apache/incubator-brooklyn/commit/14945f75b1e0a4a5cc17dbb30459d092649bf770)

**Comment by neykov** [comment]
Can you squash. Are you updating the release notes separately?

**Comment by geomacy** [comment]
Release notes updated and changes squashed.

**Comment by neykov** [comment]
LGTM, will merge.

**Pull request merged**
