### PR TITLE
Adds ArchiveUtilsTest + fixes ArchiveUtils

### PR DESCRIPTION
**Pull request by aledsage**
- Fixes case where optionalTmpDir not supplied
- Adds various test cases

### CODE REVIEW

**Comment by aledsage** [comment]
Motivated by the fix in https://github.com/apache/incubator-brooklyn/pull/472 by @michaeldye - tests that scenario, and various others.

@michaeldye If you get a chance to review + comment on this PR, that would be great!

**Comment by aledsage** [comment]
Doh, tests fail when run as unit tests, because the test server isn't setup to be able to ssh. I'll have to mark those tests as `@test(groups="Integration")`, so they are only run on test servers that are set up for ssh.

**Comment by ahgittin** [comment]
LGTM.  @michaeldye ?

**Comment by michaeldye** [comment]
Sorry for the delay. Yup, looks good to me too.

**Comment by aledsage** [comment]
Thanks @michaeldye @ahgittin - merging.

**Pull request merged**
