### PR TITLE
[BROOKLYN-183] Fix brooklyn-itest

### PR DESCRIPTION
**Pull request by CMoH**
Unfortunately pax-exam-testng is not yet usable. We decided to switch to the junit runner until this gets resolved upstream (see https://ops4j1.jira.com/browse/PAXEXAM-698)

### CODE REVIEW

**Comment by hzbarcea** [comment]
Not sure why Jenkins failed. The itest project has an explicit dependency on 
```
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>apache-brooklyn</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
            <scope>test</scope>
        </dependency>
```
So it should have been built first. I also removed org/apache/brooklyn from my local .m2 repo and tested successfully. Reviewing now.

**Comment by hzbarcea** [comment]
Reviewed, fairly straightforward. Please take care of the ```TODO``` in a future PR.

I don't know where support for testng is on the paxexam crew's roadmap. Not sure what the best way to track this is. I will ask one of the ops4j guys, but we may have to contribute that ourselves if we want that soon.

Looks good, merging.

**Comment by sjcorbett** [comment]
@hzbarcea @CMoH Jenkins is having trouble with this PR and because it's merged it's causing knock-on failures in others.
```
Test Result (2 failures / ±0)
org.apache.brooklyn.AssemblyTest.org.apache.brooklyn.AssemblyTest
org.apache.maven.surefire.junit4.JUnit4Provider.org.apache.brooklyn.AssemblyTest
```
It builds fine locally for me.

**Comment by CMoH** [comment]
Yeah - I spotted it too. I'll try to implement it properly today, or disable brooklyn-itest if not possible.

**Comment by CMoH** [comment]
@sjcorbett Attempt to fix this itest problem in #1078; jenkins is starting the build, and I hope it works. We should continue this issue over there.

**Pull request merged**
