### PR TITLE
Various QA changes

### PR DESCRIPTION
**Pull request by Graeme-Miller**
Added LoopOverGroupMembersTestCase. Removed some targeting functionality from BaseTest and added it to a new Interface called TargetabeTestComponent

Made TestCase and ParallelTestCase TargetabeTestComponent
InfrastructureDeploymentTestCaseImpl can now deploy multiple specs
TestEffector will now check assertions
InfrastructureDeploymentTestCaseImpl made more resilient

### CODE REVIEW

**Comment by m4rkmckenna** [comment]
looks good to me

**Comment by ahgittin** [comment]
Can you update docs for this?

**Comment by Graeme-Miller** [comment]
@ahgittin didn't have time to do docs today, but will look at getting them done tomorrow.
Is it worth merging this in now before the repo split and I can raise a separate PR for the documentation update?

**Comment by Graeme-Miller** [comment]
@ahgittin docs updated

**Pull request merged**
