### PR TITLE
Reverting changes made in #1060 and fixed root cause

### PR DESCRIPTION
**Pull request by m4rkmckenna**
I incorrectly diagnosed the issue in #1060 ... so changes made reverted

Root cause was due to Swagger updates made in #1040 
`@ApiOperation()` annotation on `CatalogApi#create` had response type set to `javax.ws.rs.core.Response` causing the BrooklynApi to try and marshall the returned entity to that type

### CODE REVIEW

**Comment by ahgittin** [comment]
rest client tests timed out in jenkins, while tearing down a test i think:

```
TESTNG PASSED: "Surefire test" - org.apache.brooklyn.rest.client.BrooklynApiRestClientTest.testLocationApi() finished in 18 ms
2015-11-24 23:20:02,295 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @AfterClass org.apache.brooklyn.rest.client.BrooklynApiRestClientTest.tearDown()
Build timed out (after 40 minutes). Marking the build as aborted.
```

smells related.  otherwise the work here looks straightforward.

**Comment by m4rkmckenna** [comment]
From having run locally I get the below log ... no failure but `GC (Allocation Failure)` is interesting can any one shed any light on this? From what i understand java is trying to allocate memory and failing so GC is kicking in (this may be unrelated) 
```
2015-11-25 10:46:45,697 INFO  TESTNG PASSED: "Surefire test" - org.apache.brooklyn.rest.client.BrooklynApiRestClientTest.testLocationApi() finished in 8 ms
2015-11-25 10:46:45,698 INFO  TESTNG INVOKING CONFIGURATION: "Surefire test" - @AfterClass org.apache.brooklyn.rest.client.BrooklynApiRestClientTest.tearDown()
SUREFIRE-859: [GC (Allocation Failure)  217399K->33627K(753664K), 0.0062667 secs]
SUREFIRE-859: [GC (Allocation Failure)  230235K->45522K(755712K), 0.0161661 secs]
SUREFIRE-859: [GC (Allocation Failure)  255442K->63523K(760320K), 0.0228548 secs]
SUREFIRE-859: [GC (Allocation Failure)  273443K->77064K(726528K), 0.0192347 secs]
SUREFIRE-859: [GC (Allocation Failure)  253192K->88147K(729088K), 0.0135007 secs]
SUREFIRE-859: [GC (Allocation Failure)  264275K->88834K(743424K), 0.0113851 secs]
SUREFIRE-859: [GC (Allocation Failure)  264450K->89195K(742912K), 0.0091640 secs]
2015-11-25 10:46:47,978 INFO  TESTNG PASSED CONFIGURATION: "Surefire test" - @AfterClass org.apache.brooklyn.rest.client.BrooklynApiRestClientTest.tearDown() finished in 2281 ms
```

**Comment by neykov** [comment]
@m4rkmckenna It's unrelated.
My understanding of the issue (https://issues.apache.org/jira/browse/SUREFIRE-859) is that surefire is consuming the output of the test process when it sees unexpected format, caused by verbose garbage collection (configured by us). So it will just print the unrecognized output as is.

The output itself means that the garbage collector has kicked in because of a failure to allocate a buffer, giving some statistics about the gc run.

Just ignore it.

**Comment by Tibor17** [comment]
In Surefire 2.19 the prefix "SUREFIRE-859: " was removed.

**Comment by m4rkmckenna** [comment]
Cheers @neykov & @Tibor17 

@ahgittin This looks like it was environmental as the previous [build](https://builds.apache.org/job/incubator-brooklyn-pull-requests/2229/) ABORTED also but for a different reason .... how do you want to proceed?

**Comment by Tibor17** [comment]
You have any issue with Surefire output some bug caused by Surefire?
Do you really need -verbose:gc?

**Comment by ahgittin** [comment]
@m4rkmckenna passing now, i'll merge it

@Tibor17 there was a period where bugs might get introduced which generate OOME so the GC logging was useful; hasn't been for a while, maybe we should remove

**Pull request merged**
