### PR TITLE
[BROOKLYN-162] Refactor package in ./core/util

### PR DESCRIPTION
**Pull request by hzbarcea**

### CODE REVIEW

**Comment by aledsage** [comment]
@hzbarcea can you kick off asfbot again please (e.g. by closing + reopening PR)?

From the stdout, the build looks like it succeeded, but then finished with:

    Waiting for Jenkins to finish collecting data
    Build timed out (after 40 minutes). Marking the build as aborted.
    channel stopped
    Build was aborted
    Putting comment on the pull request
    Finished: ABORTED

Normally the last lines are:

    Waiting for Jenkins to finish collecting data
    channel stopped
    Putting comment on the pull request
    Finished: SUCCESS

**Comment by aledsage** [comment]
Looks good to merge other than that asfbot build failure. In fact, can we conclude that the build really was successful (and that it was just an asfbot strangeness) given that the build stdout did say the usual:

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 17:04.069s
    [INFO] Finished at: Mon Aug 17 08:41:15 UTC 2015
    [INFO] Final Memory: 94M/237M
    [INFO] ------------------------------------------------------------------------

**Comment by hzbarcea** [comment]
@aledsage, since this is not merged I'll follow your initial request and re-open.

**Comment by hzbarcea** [comment]
The @asfbot tests passed and a re-test against a current master passes too. I am merging it to avoid a painful conflict resolution.

I also opened a ticket for infra to look into the [jenkins builds](https://issues.apache.org/jira/browse/BUILDS-107) status.

**Comment by aledsage** [comment]
@hzbarcea there are merge conflicts - can you rebase with master and then merge please?

**Comment by ahgittin** [comment]
merge conflicts are easily resolved; have merged and tested locally, so merge-closing

**Pull request merged**
