### PR TITLE
Updated JClouds to 1.9.2

### PR DESCRIPTION
**Pull request by Graeme-Miller**

### CODE REVIEW

**Comment by andreaturli** [comment]
@Graeme-Miller the failure doesn't look related to your [PR](https://builds.apache.org/job/incubator-brooklyn-pull-requests/2410/consoleText)

**Comment by Graeme-Miller** [comment]
@andreaturli yeah looks like we sometimes get a failure in org.apache.brooklyn.AssemblyTest.checkBrooklynCoreFeature.

What's the protocol here? Re-run the test? Should I look at fixing it?

**Comment by andreaturli** [comment]
Not sure we have a protocol, but best practice seems to be accept this PR, and then fix the failed test in a subsequent dedicated PR.

@aledsage any thoughts on this?

**Comment by sjcorbett** [comment]
Generally I file an issue at JIRA (e.g. [BROOKLYN-206](https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=50&view=detail&selectedIssue=BROOKLYN-206)) and force a test re-run by opening and closing the PR.

**Comment by grkvlt** [comment]
@Graeme-Miller @andreaturli @sjcorbett It looks like the failure is unrelated, so I'd like to merge this anyway

**Comment by sjcorbett** [comment]
Tests passed second time round so fine with me.

**Comment by grkvlt** [comment]
@sjcorbett great, thanks

**Comment by grkvlt** [comment]
Deploying a 0.9.0-SNAPSHOT release to https://repository.apache.org/content/repositories/snapshots

**Pull request merged**
