### PR TITLE
Updates to Riak for Clocker

### PR DESCRIPTION
**Pull request by grkvlt**
Fixes some issues with Riak on Clocker. Replaces #562

### CODE REVIEW

**Comment by bostko** [comment]
The changes and the re-factoring are very good!
Although it seems there is nothing harmful, did you have a chance to test it?

**Comment by grkvlt** [comment]
@bostko I'm testing now... Will let you know...

**Comment by grkvlt** [comment]
(Ignoring secod build failure!)

**Comment by grkvlt** [comment]
OK, looks good to me, tested on a Clocker deployment with no config set, and then with `riak.networking.optimize: false` set, both worked.

**Comment by andreaturli** [comment]
thanks @grkvlt !

**Pull request merged**
