### PR TITLE
Boolean effector parameters are rendered as checkboxes.

### PR DESCRIPTION
**Pull request by sjcorbett**
.. in jsgui.

### CODE REVIEW

**Comment by neykov** [comment]
What if we want to pass a null value? Should we use a tri-state checkbox?

**Comment by sjcorbett** [comment]
Is there really a valid case for requiring true/false/null? If someone does that they need to revisit how they design things. If there's an existing case that relies on a Boolean being null I will revisit.

**Comment by neykov** [comment]
I don't know of any, just wanted to point out this (theoretical) possibility. Since it's a UI only convenience and doesn't prevent one from passing null through other means I am all for it.

**Comment by sjcorbett** [comment]
It's a good one. Thanks for raising it. I'll ask the mailing list first.

**Comment by sjcorbett** [comment]
Screenshot:

screen shot 2015-07-17 at 12 10 42

**Comment by neykov** [comment]
No objections on the mailing list. Good to merge.

**Comment by aledsage** [comment]
Thanks all; merging.

**Pull request merged**
