### PR TITLE
brooklyn-software-database: add org.apache package prefix

### PR DESCRIPTION
**Pull request by CMoH**
Refs BROOKLYN-162

Integration tests work fine for brooklyn-software-database. mvn clean install succeeded

Changes span from java code to examples, yaml blueprients and documentation.

### CODE REVIEW

**Comment by aledsage** [comment]
Thanks @CMoH - merging.

**Comment by aledsage** [comment]
Doh, I'm not merging yet - there are conflicts. Can you resolve those first please?

**Comment by CMoH** [comment]
@aledsage I rebased. I hope no more conflicts were produced in the meantime.

**Comment by ahgittin** [comment]
LGTM, merging

**Pull request merged**
