### PR TITLE
Use the SUBNET_HOSTNAME sensor to access load balanced cluster members

### PR DESCRIPTION
**Pull request by grkvlt**

### CODE REVIEW

**Comment by sjcorbett** [comment]
@grkvlt Anything going on this?

**Comment by ahgittin** [comment]
@grkvlt i applied the same fix and a few other bits needed (including to fix the failing test) in f68bf830ffee6bd98dc6455df73db1f1faf29f12

can we close this?

**Comment by ahgittin** [comment]
@grkvlt bump

**Comment by grkvlt** [comment]
@ahgittin I am closing this as no longer required

**Pull request closed without merging**
