### PR TITLE
Adds mysql test for templating (and converts from groovy to java)

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by aledsage** [comment]
@nakomis can you review please?

**Comment by nakomis** [comment]
LGTM, tests pass

**Comment by aledsage** [comment]
Thanks; merging.

**Comment by aledsage** [comment]
Actually; I will wait for jenkins to confirm (given previous test aborted for some reason):

    Caused by: java.lang.IllegalStateException: Invalid object ID 28 iota=55
        at hudson.remoting.ExportTable.diagnoseInvalidId(ExportTable.java:346)

 Closing and re-opening PR to kick off build again.

**Pull request merged**
