### PR TITLE
BROOKLYN-212 fix

### PR DESCRIPTION
**Pull request by aledsage**
See https://issues.apache.org/jira/browse/BROOKLYN-212

### CODE REVIEW

**Comment by johnmccabe** [comment]
You can still produce onfire member entities as follows:
- Use  [this](https://gist.github.com/johnmccabe/327a9f2a208a5cb4dd52) catalog in place of the default (`./bin/brooklyn launch --catalogInitial file:///path/to/bom`)
- Deploy template 4 from above, setting the `maxPoolSize:` to exceed the number of nodes in your byon pool
- Navigate to the balancer endpoint and repeatedly hit refresh in your browser, you should observe the cluster quickly scaling up before on fire members start appearing.

**Comment by aledsage** [comment]
@johnmccabe this should fix the problems you saw, and that we discussed. Can you review+test again please?

**Comment by johnmccabe** [comment]
@aledsage that looks good with no on-fire entities observed !!

Observed the following with `maxPoolSize` to 5 and only 3 nodes available in the pool: 
- completed resize task from 1-3
- completed resize task from 3-5
  - which has a failed child task `starting 2 nodes (parallel)`.

```
org.apache.brooklyn.util.exceptions.CompoundRuntimeException: 2 of 2 parallel child tasks failed, 2 errors including: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at BasicApplicationImpl{id=kYMCHlUI}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: Error invoking start at VanillaSoftwareProcessImpl{id=NBfPZEAU}: org.apache.brooklyn.util.exceptions.PropagatedRuntimeException: org.apache.brooklyn.api.location.NoMachinesAvailableException: No machines available in FixedListMachineProvisioningLocation{id=l6QbvlPY, name=FixedListMachineProvisioningLocation:l6Qb}
```
Also observe the suppressing warning in logs:
```
2016-01-14 13:15:56,504 WARN  AutoScalerPolicy(Auto-scaler) failed to resize DynamicClusterImpl{id=AIvl1Kpr} due to insufficient capacity; setting high-water mark to 3, and will not attempt to resize above that level again
```

**Comment by aledsage** [comment]
Great, thanks @johnmccabe - any comments on the code, or is it good to merge?

**Comment by johnmccabe** [comment]
planning on reviewing later tonight @aledsage, if that suits

**Comment by aledsage** [comment]
Merging now - @johnmccabe if you have any additional comments then ping me, and I'll incorporate those in a subsequent PR.

**Pull request merged**
