### PR TITLE
Swift object store - don't use application/directory markers

### PR DESCRIPTION
**Pull request by neykov**
Softlayer object store doesn't like the content type - can't delete the folders even from its own UI.

The PR is meant to trigger a discussion on the problem more than for merging right away.

### CODE REVIEW

**Comment by sjcorbett** [comment]
@neykov Was there any discussion? May be worth writing to the mailing list instead.

**Comment by aledsage** [comment]
@neykov I agree with @sjcorbett - is this a bug we should raise with jclouds? We can fix it in our code base if necessary (and look to get it into jclouds longer term), but would be good to have a bug report in jclouds if that is appropriate.

**Comment by neykov** [comment]
It's not a bug in jclouds code. More like an implementation inconsistency in SL's objectstore.

If I remember correctly calling setContentType(directory) would make it impossible to delete the folder even through SL's UI. I need to look into the failing tests before getting this further.

**Comment by ahgittin** [comment]
close this PR for now?  possibly needs to be taken up with SL to understand what the recommended approach is, and then implement that either here or in jclouds.

**Comment by neykov** [comment]
For persistence we don't need folder markers. Instead of using explicit folder objects, just drop them altogether.

**Comment by neykov** [comment]
Looks like SL fixed their implementation as now it's possible to delete the folders and download change.log & master. This makes the changes in this PR obsolete.

**Pull request closed without merging**
