### PR TITLE
brooklyn-software-messaging: add org.apache package prefix

### PR DESCRIPTION
**Pull request by CMoH**
Refs BROOKLYN-162

Integration tests succeed.

### CODE REVIEW

**Comment by hzbarcea** [comment]
Failing tests. @CMoH, could you please check what's missing?

**Comment by CMoH** [comment]
I think it's due to the order the PRs were merged. I'm re-checking and will update the PR soon.

**Comment by ygy** [comment]
Indeed. 
It is better to have only one PR regarding 'software/messaging'. I will close mine since it was created a little bit later.

**Comment by CMoH** [comment]
In effect, I missed the examples folder. Please retry.

**Comment by aledsage** [comment]
@CMoH there are merge conflicts - can you rebase against master please?

**Comment by CMoH** [comment]
@aledsage I rebased this PR as well.

**Comment by CMoH** [comment]
I wonder why these builds keep getting aborted. From the console of the build above I can see only a timeout:

```
Parsing POMs
Downloaded artifact http://repo.maven.apache.org/maven2/org/apache/apache/17/apache-17.pom
Modules changed, recalculating dependency graph
Build timed out (after 40 minutes). Marking the build as aborted.
Build was aborted
Putting comment on the pull request
```

It feels like a systemic problem on the build host.

**Comment by CMoH** [comment]
I've rebased this PR again. Can someone test and merge it before new conflicts arise?

**Comment by ahgittin** [comment]
looking at this now

**Comment by ahgittin** [comment]
LGTM, merging

**Pull request merged**
