### PR TITLE
Entitlements - effector args and catalog access

### PR DESCRIPTION
**Pull request by ahgittin**
allows filtering based on arguments to effectors, access to catalog, and cleans up the pattern by which entitlement-supplying classes can be written

### CODE REVIEW

**Comment by ahgittin** [comment]
rebased on master including #414, resolving merge conflicts. ready for review /cc @nakomis

**Comment by ahgittin** [comment]
ping @nakomis @aledsage - would be nice to close this!

**Comment by ahgittin** [comment]
ping [DUP] @nakomis @aledsage

**Comment by ahgittin** [comment]
ping [DUP] @nakomis @aledsage

**Comment by nakomis** [comment]
LGTM, and tests pass

**Pull request merged**
