### PR TITLE
Put OSGi test deps back

### PR DESCRIPTION
**Pull request by ahgittin**
This updates all the OSGi and JAR tests which were moved and disabled in #810.  They are in the original places for want of anything better as discussed there.  @rdowner this should save you any more build-fix-version-mismatch woes (though now likely you've solved them)!

Tests not yet passing, for early review only

### CODE REVIEW

**Comment by ahgittin** [comment]
tests seem fixed now, for me.  @hzbarcea does this fix things for you?

**Comment by ahgittin** [comment]
the cassandra failure in #1721 is concerning, it doesn't look remotely relevant to this work /cc @aledsage 

the one after it is happy so this PR is good to go

**Comment by aledsage** [comment]
@ahgittin Thanks - looks good; merging.

**Comment by hzbarcea** [comment]
I reviewed and tested too, @aledsage beat me to it.

**Pull request merged**
