### PR TITLE
reorganise project structure in preparation for repository split

### PR DESCRIPTION
**Pull request by johnmccabe**
This pull applies the pre-repository-split restructuring script `1-rearrange-incubator.sh` from rdowner/brooklyn-repo-split#5, and updates maven/tests accordingly.

Once applied the project will be structured in preparation for the split into multiple git repositories (`brooklyn-server`, `brooklyn-ui`, `brooklyn-library`, `brooklyn-dist`, `brooklyn`).

A verbose commit history is maintained for reference with each commit prefixed by the impacted submodule, ie [SERVER], [LIBRARY] etc. (_Note the work-in-progress repo was originally located [here](https://github.com/johnmccabe/PRESPLIT-incubator-brooklyn)._)

The project can be built as normal, with a brooklyn pom in the root of the repository.

You may also build each submodule in turn, `brooklyn-ui`, `brooklyn-server`, `brooklyn-library` and finally `brooklyn-dist`. The brooklyn subdirectory will eventually become the split repo base project,.

Feedback is greatly welcomed.

---
#### Post-merge actions [7]
Once this is merged:

1. Existing branches and PR's may have to be rebased or merged
2. Your IDE may have to be completely reset

On (1) git actually does a remarkable job of tracking things across 
moves, so I expect conflicts will mainly be:

* where you have added or deleted files
* where you have changed something which has changed (especially the poms)

If you have a PR or WIP which does these it will be a bit easier to 
merge them first so please let us know.  In particular there is UI, 
OSGi, and Salt work in progress I think we were hoping to merge. But I 
don't want to hold up the migration for too long.

FYI it will be a little bit more tedious to migrate these changes across 
to the new repo structure (ie apache/brooklyn{,-*}) but git-patch 
assuming we keep the same filesystem structure using git modules should 
work pretty well once you have rebased on the reorged incubator project.

---
For reference the reorg/split related email threads are listed here:

1.  [\[HEADS-UP\] Brooklyn graduation](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201511.mbox/%3C564B6794.3070800%40CloudsoftCorp.com%3E)
2. [\[DISCUSS\] new repos and project migration](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201511.mbox/%3C56563E49.3010907%40CloudsoftCorp.com%3E)
3. [\[VOTE\] migration to new apache/brooklyn* repos](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201511.mbox/%3C565643A2.1080207%40CloudsoftCorp.com%3E)
4. [\[RESULT\]\[VOTE\] migration to new apache/brooklyn* repos](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201512.mbox/%3C565DFD5F.609%40gmail.com%3E)
5. [\[IMPORTANT\]\[PLEASE-READ\] Graduation tasks and git repo changes](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201512.mbox/%3C565E16BF.4030306%40gmail.com%3E)
6. [Repository splitting script](https://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201512.mbox/%3CCABQFKi23w96TrguxWh8Kk9DC163FqKVxxoNt7ebhQpE-qquAbw%40mail.gmail.com%3E)
7. [Incubator re-org](http://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201512.mbox/%3C567550F7.4030906%40CloudsoftCorp.com%3E)

### CODE REVIEW

**Comment by ahgittin** [comment]
awesome job.  works great so far and should really simplify the migration, as much as we can.  great summary as well @johnmccabe.

i've been through all the PR's.  here is my list of things to look at:

* poms:
    * library repeats versions from software
    * test deps were commented out in many places, look like they were added but double check
    * comment why `<relativePath/>` is used
* jsgui
    * is it included correctly in Launcher
    * comment BrooklynJavascriptGuiLauncher.java 71 / load order
    * included correctly in release artifacts
    * comment in root / brooklyn POM about order
* tests
    * did java-web-app-simple.yaml vanish
    * some tests are taking a long time
* overall
    * double-check release artifacts

many are just sanity checks.  i'll keep working through these.

**Comment by ahgittin** [comment]
have ticked everything off apart from:

* poms - library repeats versions from software
* jsgui - included correctly in release artifacts
* tests - some tests are taking a long time
* overall - double-check release artifacts

working on these now

**Comment by ahgittin** [comment]
have looked in to why tests are taking significantly longer.  i fixed a few obvious items, but there seem to be two recent big offenders:

* test framework -- has a dozen or so tests which wait for 2s
* recent jetty update -- attempts DTD validation when starting a web server (half a dozen tests; worse, these fail if you are offline!)

beyond this the biggest offenders are the dozen or so methods which need to populate the catalog, each taking several seconds.  

as neither is directly related to the reorg i'll hit pause on them but recording findings for posterity, esp for @sjcorbett @aledsage 

BTW simple script (from uber repo / root) to see how long projects' tests take:

    find . -name TEST-TestSuite.xml | while read x ; do echo -n $x": " ; grep \<testsuite $x ; done | sort -k 4

and long individual test cases

    find . -name TEST-TestSuite.xml -exec cat {} \; | grep testcase | sort -k4

(sorting is not-quite-numeric but avoids messy xmllinting and sed)

i will move on to the others

**Comment by geomacy** [comment]
I have a couple of questions - 

1.  Why do we have a relativeRoot in the pom files - shouldn't we avoid  ".." in the poms and rely on the maven repo for dependencies?   It looks particularly questionable to have one repo (brooklyn-library) having a relative path dependency to *another repo* in its pom.  I would recommend we remove the relativePath from all poms and ensure the maven repository is built up in the right order.  
1. Why for that matter do projects in brooklyn-dist and brooklyn-library have a *parent pom* from inside brooklyn server - I would have thought that brooklyn-server would be a dependency but not a parent?

**Comment by ahgittin** [comment]
@geomacy the parent defines the profiles for integration tests and releases which is common to nearly all brooklyn projects.  and the way maven handles relative paths is that they are preferred to looking in the repo but it will fall back to the repo if it isn't present.  so if someone has checked out all git projects according to canonical structure, local parent pom changes will be picked up even in sibling projects without a rebuild.  this is standard practise w maven afaik and required for IDE's to resolve deps for things which haven't been built.

**Comment by ahgittin** [comment]
unusual failure, `ControlledDynamicWebAppCluster.testTheJavaWebApp()`, sensor timeout; seems spurious, will try again shortly /cc @aledsage

**Comment by sjcorbett** [comment]
@ahgittin There are a few unreliable tests on Jenkins. See https://issues.apache.org/jira/browse/BROOKLYN-203, https://issues.apache.org/jira/browse/BROOKLYN-204, https://issues.apache.org/jira/browse/BROOKLYN-205 and https://issues.apache.org/jira/browse/BROOKLYN-206.

**Comment by geomacy** [comment]
Fair enough thanks @ahgittin

**Comment by johnmccabe** [comment]
@sjcorbett @ahgittin are these intermittent failures only seen during runs on Jenkins or have you encountered then running locally?

**Comment by sjcorbett** [comment]
@johnmccabe I've seen 204 locally once or twice, none of the others.

**Comment by ahgittin** [comment]
thx @sjcorbett , you're on top of it.  it was BROOKLYN-203 which we saw here.  never seen that before.

**Comment by ahgittin** [comment]
| tests - some tests are taking a long time

as discussed -- to be fixed later but not in this PR

| poms - library repeats versions from software

done, most things removed from `library`, a few library-only things removed instead from `server`

| jsgui - included correctly in release artifacts

| overall - double-check release artifacts

confirmed things all look good.  nice work @johnmccabe 

---

assuming the jenkins check passes i think this is good to merge.  @johnmccabe maybe you can look over my changes (but really they are tiny) and then let's do it?

**Comment by johnmccabe** [comment]
:+1: lgtm, builds and tests passing, just a few trivial observations/comments.

**Comment by aledsage** [comment]
+1

**Pull request merged**
