### PR TITLE
[BROOKLYN-148] Improve policy support for catalog items

### PR DESCRIPTION
**Pull request by neykov**
* policies found through scanning the classpath will be added with the correct yaml markup
  * support for nested catalog item loading for policies, plus infinite recursion avoidance check
  * fix catalog item type detection for non-entities

### CODE REVIEW

**Comment by neykov** [comment]
Fix for https://issues.apache.org/jira/browse/BROOKLYN-148

**Comment by csabapalfi** [comment]
Looks good to me. Works locally now.

**Comment by grkvlt** [comment]
+1, looks OK to merge :frog:

**Comment by ahgittin** [comment]
good fixes, merging #668 #669 #670

**Pull request merged**
